/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gradleapp;

public class App {
    public String getGreeting() {
        Integer st=null;
        Integer st2 = st+st;
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
